{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1de55ffb",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "import os\n",
    "import re\n",
    "import pandas as pd\n",
    "import tensorflow as tf\n",
    "import seaborn as sns\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.metrics import accuracy_score"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e2f6c5e0",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using TensorFlow backend.\n"
     ]
    }
   ],
   "source": [
    "from keras.preprocessing.text import Tokenizer\n",
    "from keras.preprocessing.sequence import pad_sequences\n",
    "from keras.layers import Flatten,Dense,Embedding\n",
    "from keras import models, layers, optimizers, losses, metrics\n",
    "from keras.layers import Dropout\n",
    "from keras.optimizers import Adam\n",
    "from keras.wrappers.scikit_learn import KerasClassifier\n",
    "from keras.models import Sequential\n",
    "from keras.layers.convolutional  import  Convolution1D, MaxPooling1D\n",
    "from keras.layers import LSTM\n",
    "from keras.callbacks import LambdaCallback\n",
    "tok = Tokenizer()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "b860ff65",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "train_pos=[]\n",
    "train_neg=[]\n",
    "test_pos=[]\n",
    "test_neg=[]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "2e9c49e6",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "#imput data and make train_test_split\n",
    "def train_test_split(file_root):\n",
    "    train = []\n",
    "    test = []\n",
    "    for file_root, _, file in os.walk(file_root):\n",
    "        for f in file:\n",
    "                index = int(re.findall(\"\\d+\", f)[0])\n",
    "                file_path = os.path.join(file_root, f)\n",
    "                name = os.path.split(file_root)[-1]\n",
    "                if (index > 699):\n",
    "                    test.append(file_path)\n",
    "                else:\n",
    "                    train.append(file_path)\n",
    "    return train, test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c4510d15",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "#remove the punctuation\n",
    "def remove(text):\n",
    "    remove_chars = '[0-9’!\"#$%&\\'()*+,-./:;<=>?@，。?★、…【】《》？“”‘’！[\\\\]^_`{|}~]+'\n",
    "    return re.sub(remove_chars, '', text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "5bba0b2d",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "train_pos,test_pos=train_test_split('../Data/pos')\n",
    "train_neg,test_neg=train_test_split('../Data/neg')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "fab1e078",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "#remove \\n and combine all the string\n",
    "stri=[]#the box to hold all the words"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "0d6c909a",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "def remove_combine(data):\n",
    "    for i in range(0,len(data)):\n",
    "        f=open(data[i],'r')\n",
    "        st=f.read()\n",
    "        f.close()\n",
    "        st=remove(st)\n",
    "        st=st.replace('\\n','').replace('\\r','')\n",
    "        stri.append(st)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "3ebc757e",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "All words is 46830\n"
     ]
    }
   ],
   "source": [
    "#combine\n",
    "remove_combine(train_pos)\n",
    "remove_combine(test_pos)\n",
    "remove_combine(train_neg)\n",
    "remove_combine(test_neg)\n",
    "#print(stri)\n",
    "tok.fit_on_texts(stri)\n",
    "#print(tok.word_counts)\n",
    "all_words=len(tok.word_counts)\n",
    "print('All words is',all_words)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "5a9bad27",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The average length of review is 644.361\n",
      "The std of review is 285.0598064014157\n"
     ]
    }
   ],
   "source": [
    "#show result\n",
    "review_len=[]\n",
    "for a in range(0,len(stri)):\n",
    "    st_new=stri[a]\n",
    "    st_new=st_new.split()\n",
    "    review_len.append(len(st_new))\n",
    "df_review_len=pd.DataFrame(review_len,columns=['length'])\n",
    "print('The average length of review is',df_review_len.mean().values[0])\n",
    "print('The std of review is',df_review_len.std().values[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "61ad8b23",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAU0AAADQCAYAAACDfzPtAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAASuUlEQVR4nO3dfYxc1XnH8e8PJxAaSHgz1DG4a1NDCpG6gQVKCJCUhrcmIaQFjBAhgbKgQggtoGKoEhoJFZICTUqCaooLRLwGQ3AUEkwpAVU1LzYvxsY42Lwkzlq2WYIhQjK1efrHPYvH9p3dubs7c+/M/D7SaO6ce+/MczzrR+fMPfccRQRmZtaYbcoOwMysnThpmpkV4KRpZlaAk6aZWQFOmmZmBThpmpkV8IGyAxiL3XbbLXp6esoOw8w6zMKFC1+PiIl5+9o6afb09LBgwYKywzCzDiPptXr73D03MyvASdPMrAAnTTOzApw0zcwKcNI0Myugra+ed7P+Cy5mYHDdZmUf2/WjzPr+v5QUkVl3aFrSlDQb+DywJiI+kcruAvZNh+wEvBkRvZJ6gKXAsrTv8Yg4t1mxdYKBwXXscOSZm5c9OrukaMy6RzNbmjcD1wO3DhVExClD25KuAWqbSisioreJ8ZiZjVnTkmZEPJZakFuRJOBk4M+b9flmZs1Q1oWgw4HVEfFSTdlUSc9IelTS4SXFZWY2rLIuBJ0K3FHzehUwJSIGJR0I/ETS/hHx1pYnSuoH+gGmTJnSkmDNzIa0vKUp6QPAl4G7hsoiYn1EDKbthcAKYJ+88yNiVkT0RUTfxIm599ObmTVNGd3zvwBejIiVQwWSJkqakLanAdOBl0uIzcxsWE1LmpLuAOYD+0paKemstGsGm3fNAY4AFkl6DrgHODci3mhWbGZmo9XMq+en1in/ak7ZHGBOs2LpFouff57Pn3b2VuUe9G42fnxHUAd5N7bZasA7eNC72XjyvedmZgU4aZqZFeDuecXlTcwBsGTpMg45soSAzLqck2bF5U3MAbB+0UUlRGNm7p6bmRXglmaXqtft9/Aks+E5aXapet1+D08yG56752ZmBThpmpkV4KRpZlaAk6aZWQG+ENQF8iby8OB4s9Fp9WqUVwBnA2vTYZdFxANp30zgLGAjcEFEPNis2LpN3kQeHhxvNjrN7J7fDBybU35dRPSmx1DC3I9sns390zk/HJqU2MysSpqWNCPiMaDRiYRPAO5My168AiwHDm5WbGZmo1XGhaDzJS2SNFvSzqlsMvCbmmNWprKtSOqXtEDSgrVr1+YdYmbWNK1OmjcAewO9ZCtQXpPKlXNs5L2BF1YzszK1NGlGxOqI2BgR7wE3sqkLvhLYq+bQPYGBVsZmZtaIliZNSZNqXp4ILE7bc4EZkraTNJVsNconWxmbmVkjmjnk6A7gM8BuklYC3wI+I6mXrOv9KnAOQEQskXQ38AKwATgvIjY2KzYzs9Fq9WqUNw1z/JXAlc2KxxqTNxDe08WZbeI7gmwzeQPhPV2c2Sa+99zMrAAnTTOzApw0zcwKcNI0MyvASdPMrAAnTTOzApw0zcwKcNI0MyvASdPMrAAnTTOzApw0zcwKaPXCat8FvgC8C6wAvhYRb0rqAZYCy9Lpj0fEuc2Krar6L7iYgcF1m5V51UizamnmhB03A9cDt9aUPQTMjIgNkq4GZgL/kPatiIjeJsZTeQOD67xqpFnFtXRhtYiYFxEb0svHyWZoNzNrG2X+pnkm8POa11MlPSPpUUmHlxWUmdlwSplPU9LlZDO035aKVgFTImJQ0oHATyTtHxFv5ZzbD/QDTJkypVUhm5kBJbQ0JZ1BdoHotIgIgLTe+WDaXkh2kWifvPO9GqWZlanVC6sdS3bh54sR8U5N+URJE9L2NLKF1V5uZWxmZo1o9cJqM4HtgIckwaahRUcA35a0AdgInBsRb+S+sZlZiSqxsFpEzAHmNCsWM7Px4oXVbER5K1SCV6m07uSkaSPKW6ESvEqldSffe25mVoCTpplZAU6aZmYFOGmamRXgpGlmVoCTpplZAQ0lTUmHNVJmZtbpGm1p/luDZWZmHW3Ywe2SDgU+BUyU9Pc1uz4CTGhmYGZmVTTSHUHbAjuk43asKX8L+OtmBWVmVlXDJs2IeBR4VNLNEfFai2IyM6usRn/T3E7SLEnzJP330GO4EyTNlrRG0uKasl0kPSTppfS8c82+mZKWS1om6ZhR1sfMrKkaTZo/Bp4B/hG4pOYxnJuBY7couxR4OCKmAw+n10jaD5gB7J/O+eHQpMRmZlXS6CxHGyLihiJvHBGPpfXMa51ANjExwC3AL8lmcj8BuDMi1gOvSFoOHAzML/KZ1lp5U8Z5ujjrdI0mzZ9K+lvgPmD9UOEoZlffIyJWpXNXSdo9lU8mW9J3yMpUZhWWN2Wcp4uzTtdo0jwjPdd2yQOYNk5xKKcscg/0apRmVqKGkmZETB2nz1staVJqZU4C1qTylcBeNcftCQzUiWUWMAugr68vN7GamTVLQ0lT0lfyyiPi1oKfN5es1XpVer6/pvx2SdcCHyNbjfLJgu9tZtZ0jXbPD6rZ/hBwFPA0UDdp1lmN8irgbklnAb8GTgKIiCWS7gZeADYA50XExmJVMTNrvka751+vfS3po8CPRjgnbzVKyBJu3vFXAlc2Eo+ZWVlGOzXcO2RdaDOzrtLob5o/ZdPV7AnAnwB3NysoM7OqavQ3zdrRyhuA1yJiZRPiMTOrtIa652nijhfJZjraGXi3mUGZmVVVozO3n0w2BOgk4GTgCUmeGs7Muk6j3fPLgYMiYg2ApInAfwH3NCuwTtF/wcUMDK7brMz3Z5u1r0aT5jZDCTMZxIuyNWRgcJ3vzzbrII0mzV9IehC4I70+BXigOSGZmVXXSGsE/THZzESXSPoy8GmyyTXmA7e1ID5rM3nTxYF/krDOMVJL81+BywAi4l7gXgBJfWnfF5oYm7WhvOniwD9JWOcYKWn2RMSiLQsjYkHOBMPWoHqtsSVLl3HIkSUEZGYNGylpfmiYfduPZyDdpF5rbP2ii0qIxsyKGOkK+FOStmoSpVmKFjYnJDOz6hqppXkhcJ+k09iUJPvI1kM/cTQfKGlf4K6aomnAN4GdgLOBtan8sojwFXozq5SR1j1fDXxK0meBT6Tin0XEsMv3jvCey4BegLTi5G/J1h76GnBdRPgSq5lVVqPzaT4CPNKEzz8KWBERr0l5ywSZmVVL2Xf1zGDTgHmA8yUtkjRb0s55J0jql7RA0oK1a9fmHWJm1jSlJU1J2wJfBH6cim4A9ibruq8Crsk7LyJmRURfRPRNnDixFaGamb2vzJbmccDT6XdTImJ1RGyMiPeAG4GDS4zNzCxXmUnzVGq65mlJ3yEnAotbHpGZ2QganbBjXEn6A+BzwDk1xd+R1Eu2rMarW+wzM6uEUpJmRLwD7LpF2ellxGJmVkTZV8/NzNqKk6aZWQGldM87Ud6yFuCZi8w6jZPmOMlb1gI8c5FZp3H33MysALc0rSXyJl72EhjWjpw0rSXyJl72EhjWjtw9NzMrwEnTzKwAJ00zswKcNM3MCnDSNDMroKxZjl4F3gY2Ahsiok/SLmQLrvWQzXJ0ckT8roz4zMzqKbOl+dmI6I2IvvT6UuDhiJgOPJxem5lVSpW65ycAt6TtW4AvlReKmVm+spJmAPMkLZTUn8r2iIhVAOl595JiMzOrq6w7gg6LiAFJuwMPSXqx0RNTku0HmDJlSrPiMzPLVUpLMyIG0vMa4D6yRdRWD60TlJ7X1DnXq1GaWWlanjQlfVjSjkPbwNFki6jNBc5Ih50B3N/q2MzMRlJG93wP4D5JQ59/e0T8QtJTwN2SzgJ+DZxUQmxmZsNqedKMiJeBP80pHwSOanU8ZmZFVGnIkZlZ5TlpmpkV4KRpZlaAZ2630uQtgQFeBsOqzUnTSpO3BAZ4GQyrNnfPzcwKcNI0MyvASdPMrAAnTTOzApw0zcwK8NVz6zj9F1zMwOC6rco9lMnGg5OmdZyBwXUeymRN46Q5CnktmSVLl3HIkSUF1GHyBr3XayX6u7BWa3nSlLQXcCvwh8B7wKyI+J6kK4CzgbXp0Msi4oFWx9eIvJbM+kUXlRRN58kb9F6vlejvwlqtjJbmBuCiiHg6TUa8UNJDad91EeEfncysssqYT3MVMLSA2tuSlgKTWx2HmdlolDrkSFIP8EngiVR0vqRFkmZL2rnOOf2SFkhasHbt2rxDzMyaprSkKWkHYA5wYUS8BdwA7A30krVEr8k7zwurmVmZSkmakj5IljBvi4h7ASJidURsjIj3gBvJVqg0M6uUMq6eC7gJWBoR19aUT0q/dwKcSLZCpRlQf+5NDy+yVivj6vlhwOnA85KeTWWXAadK6gUCeBU4p4TYrKLqzb3p4UXWamVcPf8fQDm7Kjkm08yslifsMDMrwEnTzKwAJ00zswI8YYd1NU8jZ0U5aVpX8zRyVpS752ZmBbilaV0jb4B8vcHxece+/KsXmbbPx7c61l357uKkaV0jb4B8vcHxece+uegid+XNSXM49S4S+NY9s+7lpDmMehcJfOue1SqyPIe1PydNszHK68rPu/7vcicYcTJtf06aZk1Qb4KRvN8/PVa0vVQuaUo6FvgeMAH4j4i4quSQzMZN3Sv451691bFjvcDkZNwclUqakiYAPwA+B6wEnpI0NyJeKDcys/FR5Ap+nnqJMG84VL1k7J8OxqZSSZNstvblEfEygKQ7gROAcUuahf/ofJXcSlKkVZo3HKrIcCrw0KlGVS1pTgZ+U/N6JXDIeH5AvSviRf7ozFphrK3SoqowCiCvUVMvhrxjW3EDgiJiXN5oPEg6CTgmIv4mvT4dODgivl5zTD/Qn17uCyxr8O13A14fx3CrwvVqL65Xe/ijiMhdubFqLc2VwF41r/cEBmoPiIhZwKyibyxpQUT0jS286nG92ovr1f6qNmHHU8B0SVMlbQvMAOaWHJOZ2fsq1dKMiA2SzgceJBtyNDsilpQclpnZ+yqVNAEi4gGas8ha4S59m3C92ovr1eYqdSHIzKzqqvabpplZpXVF0pR0rKRlkpZLurTseIqS9Kqk5yU9K2lBKttF0kOSXkrPO9ccPzPVdZmkY8qLfHOSZktaI2lxTVnhekg6MP17LJf0fUlqdV1q1anXFZJ+m76zZyUdX7Ov8vWStJekRyQtlbRE0jdSedt/X2MWER39ILugtAKYBmwLPAfsV3ZcBevwKrDbFmXfAS5N25cCV6ft/VIdtwOmprpPKLsOKbYjgAOAxWOpB/AkcCgg4OfAcRWs1xXAxTnHtkW9gEnAAWl7R+BXKfa2/77G+uiGlub7t2ZGxLvA0K2Z7e4E4Ja0fQvwpZryOyNifUS8Aiwn+zcoXUQ8BryxRXGhekiaBHwkIuZH9j/y1ppzSlGnXvW0Rb0iYlVEPJ223waWkt2x1/bf11h1Q9LMuzVzckmxjFYA8yQtTHdEAewREasg+wMHdk/l7VbfovWYnLa3LK+i8yUtSt33oW5s29VLUg/wSeAJOvv7akg3JM2830/abcjAYRFxAHAccJ6kI4Y5thPqC/Xr0S71uwHYG+gFVgHXpPK2qpekHYA5wIUR8dZwh+aUVbZeY9ENSXPEWzOrLiIG0vMa4D6y7vbq1PUhPa9Jh7dbfYvWY2Xa3rK8UiJidURsjIj3gBvZ9BNJ29RL0gfJEuZtEXFvKu7I76uIbkiabX1rpqQPS9pxaBs4GlhMVocz0mFnAPen7bnADEnbSZoKTCf7Ib6qCtUjdQnflvRn6SrsV2rOqYyhxJKcSPadQZvUK8VwE7A0Iq6t2dWR31chZV+JasUDOJ7s6t8K4PKy4ykY+zSyq5LPAUuG4gd2BR4GXkrPu9Scc3mq6zIqdKUSuIOsq/p/ZC2Qs0ZTD6CPLAmtAK4n3aRRsXr9CHgeWESWUCa1U72AT5N1oxcBz6bH8Z3wfY314TuCzMwK6IbuuZnZuHHSNDMrwEnTzKwAJ00zswKcNM3MCnDStLYi6fdNeM/eLWYhukLSxeP9OdYZnDTNslsdjx/pIDNw0rQ2JukSSU+lSTH+KZX1pDkgb0zzQM6TtH3ad1A6dr6k70panO4S+zZwSpr38pT09vtJ+qWklyVdUFIVrYKcNK0tSTqa7Fa9g8laigfWTGQyHfhBROwPvAn8VSr/T+DciDgU2AgQ2XSB3wTuiojeiLgrHftx4Jj0/t9K92GbOWla2zo6PZ4BniZLctPTvlci4tm0vRDokbQTsGNE/G8qv32E9/9ZZHNDvk42KcUe4xi7tbHKrUZp1iAB/xwR/75ZYTb34/qaoo3A9uRPUTacLd/D/1cMcEvT2teDwJlpvkckTZa0e72DI+J3pNl2UtGMmt1vky3pYDYiJ01rSxExj6yLPV/S88A9jJz4zgJmSZpP1vJcl8ofIbvwU3shyCyXZzmyriFph4j4fdq+lGy6tm+UHJa1Gf9OY93kLyXNJPu7fw34arnhWDtyS9PMrAD/pmlmVoCTpplZAU6aZmYFOGmamRXgpGlmVoCTpplZAf8PggMBKSXC+uUAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 360x216 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.figure(figsize=(5,3))\n",
    "sns.histplot(data=df_review_len, x='length')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "91670b4d",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[  98 2272 8121 ...    0    0    0]\n",
      " [  61   65 1967 ...    0    0    0]\n",
      " [   1   66    4 ...    0    0    0]\n",
      " ...\n",
      " [1385 2280    6 ...    0    0    0]\n",
      " [ 152 4698   30 ...    0    0    0]\n",
      " [  23  685    5 ...    0    0    0]]\n"
     ]
    }
   ],
   "source": [
    "#data transfrom\n",
    "data_trans=tok.texts_to_sequences(stri)\n",
    "df_review_len_sort=df_review_len.sort_values(by='length')\n",
    "max_num=df_review_len_sort.iloc[int(len(review_len)*0.9),:].values[0] #choose max_length\n",
    "data_trans_true=pad_sequences(data_trans,maxlen=max_num,padding ='post',truncating='post')\n",
    "print(data_trans_true)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "ddeb3508",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "#train_test_split\n",
    "df_raw_data=pd.DataFrame(data_trans_true)\n",
    "x_train1=df_raw_data.iloc[:700,:]\n",
    "x_test1=df_raw_data.iloc[700:1000,:]\n",
    "x_train2=df_raw_data.iloc[1000:1700,:]\n",
    "x_test2=df_raw_data.iloc[1700:,:]\n",
    "x_train=pd.concat([x_train1,x_train2])\n",
    "x_test=pd.concat([x_test1,x_test2])\n",
    "x_train=pd.DataFrame(x_train.values)\n",
    "x_test=pd.DataFrame(x_test.values)\n",
    "x_train[x_train>=5000]=0\n",
    "x_test[x_test>=5000]=0\n",
    "y_train1=list(1 for i in range(1,701))\n",
    "y_train2=list(-1 for i in range(1,701))\n",
    "y_train=y_train1+y_train2\n",
    "y_test1=list(1 for i in range(1,301))\n",
    "y_test2=list(-1 for i in range(1,301))\n",
    "y_test=y_test1+y_test2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "a0b4cc5e",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "#mix up train_data\n",
    "indices=np.arange(x_train.shape[0])\n",
    "np.random.shuffle(indices)\n",
    "y_train=pd.DataFrame(y_train)\n",
    "x_train=x_train.loc[indices]\n",
    "y_train=y_train.loc[indices]\n",
    "x_train=x_train.values\n",
    "x_test=x_test.values"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "140fae9b",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "#mlp\n",
    "def mlp(opt='adam'):\n",
    "    model = Sequential()\n",
    "    model.add(Embedding(5001, 32, input_length=max_num))\n",
    "    model.add(Flatten())\n",
    "    model.add(Dropout(rate=0.2))\n",
    "    model.add(Dense(units=50, activation='relu'))\n",
    "    model.add(Dropout(rate=0.5))\n",
    "    model.add(Dense(units=50, activation='relu'))\n",
    "    model.add(Dropout(rate=0.5))\n",
    "    model.add(Dense(units=50, activation='relu'))\n",
    "    model.add(Dropout(rate=0.5))\n",
    "    model.add(Dense(units=1, activation='sigmoid'))\n",
    "    model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "0f693cca",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "def acc_result(x_tr,x_te,y_tr,y_te,classifier,num_epochs):\n",
    "    mlp_model = KerasClassifier(build_fn=classifier, epochs=num_epochs, batch_size=10)\n",
    "    mlp_model.fit(x_tr,y_tr)\n",
    "    y_train_predict_mlp = mlp_model.predict(x_tr)\n",
    "    y_test_predict_mlp = mlp_model.predict(x_te)\n",
    "    train_acc = accuracy_score(y_tr,y_train_predict_mlp)\n",
    "    test_acc = accuracy_score(y_te,y_test_predict_mlp)\n",
    "    return train_acc, test_acc,y_train_predict_mlp,y_test_predict_mlp"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "53e826f8",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/2\n",
      "1400/1400 [==============================] - 9s 6ms/step - loss: 0.6991 - accuracy: 0.5029\n",
      "Epoch 2/2\n",
      "1400/1400 [==============================] - 7s 5ms/step - loss: 0.6873 - accuracy: 0.5350\n",
      "Using mlp models, the train set accuracy is:0.7193, the test set accuracy is 0.54.\n"
     ]
    }
   ],
   "source": [
    "#print the result of mlp\n",
    "mlp_train_acc,mlp_test_acc,y_p_train_mlp,y_p_test_mlp= acc_result(x_train,x_test,y_train,y_test,mlp,2)\n",
    "print('Using mlp models, the train set accuracy is:{}, the test set accuracy is {}.'.\n",
    "      format(round(mlp_train_acc,4),round(mlp_test_acc,4)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "ec247d6a",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "#CNN\n",
    "def CNN(opt='adam'):\n",
    "    model = Sequential()\n",
    "    model.add(Embedding(5001, 32, input_length=max_num))\n",
    "    model.add(Convolution1D(32,3,activation='relu'))\n",
    "    model.add(MaxPooling1D(strides=2,pool_size=2))\n",
    "    model.add(Flatten())\n",
    "    model.add(Dropout(rate=0.2))\n",
    "    model.add(Dense(units=50, activation='relu'))\n",
    "    model.add(Dropout(rate=0.5))\n",
    "    model.add(Dense(units=50, activation='relu'))\n",
    "    model.add(Dropout(rate=0.5))\n",
    "    model.add(Dense(units=50, activation='relu'))\n",
    "    model.add(Dropout(rate=0.5))\n",
    "    model.add(Dense(units=1, activation='sigmoid'))\n",
    "    model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "46cf0a4f",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/2\n",
      "1400/1400 [==============================] - 9s 7ms/step - loss: 0.6966 - accuracy: 0.5014\n",
      "Epoch 2/2\n",
      "1400/1400 [==============================] - 7s 5ms/step - loss: 0.6922 - accuracy: 0.5293\n",
      "Using cnn models, the train accuracy is:0.6521, the test accuracy is 0.5633.\n"
     ]
    }
   ],
   "source": [
    "cnn_train_acc,cnn_test_acc,y_p_train_cnn,y_p_test_cnn=acc_result(x_train,x_test,y_train,y_test,CNN,2)\n",
    "print('Using cnn models, the train accuracy is:{}, the test accuracy is {}.'.format(round(cnn_train_acc,4),round(cnn_test_acc,4)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "faf8ba64",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "#LSTM\n",
    "def LSTM_model(opt='adam'):\n",
    "    model = Sequential()\n",
    "    model.add(Embedding(5001, 32, input_length=max_num))\n",
    "    #model.add(Dropout(rate=0.2))\n",
    "    model.add(LSTM(32, return_sequences=True,activation='relu',dropout=0.2))\n",
    "    model.add(Flatten())\n",
    "    model.add(Dropout(rate=0.2))\n",
    "    model.add(Dense(units=256, activation='relu'))\n",
    "    model.add(Dropout(rate=0.2))\n",
    "    model.add(Dense(units=1, activation='sigmoid'))\n",
    "    adam_optimizer = Adam(lr=0.0001, beta_1=0.5)\n",
    "    model.compile(optimizer=adam_optimizer, loss='binary_crossentropy', metrics=['accuracy'])\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3e7363f8",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "If using Keras pass *_constraint arguments to layers.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "If using Keras pass *_constraint arguments to layers.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.where in 2.0, which has the same broadcast rule as np.where\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.where in 2.0, which has the same broadcast rule as np.where\n",
      "2022-05-10 10:08:06.039033: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA\n",
      "To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-05-10 10:08:06.039551: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/50\n",
      "1400/1400 [==============================] - 550s 393ms/step - loss: 0.6953 - accuracy: 0.5093\n",
      "Epoch 2/50\n",
      " 710/1400 [==============>...............] - ETA: 5:51 - loss: 0.6869 - accuracy: 0.5577"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/9g/15wmnj2j4913201hs60_m1sh0000gn/T/ipykernel_74337/344838209.py\", line 5, in <module>\n",
      "    lstm_iter_model.fit(x_train,y_train,callbacks=[save_point])\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/wrappers/scikit_learn.py\", line 209, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/wrappers/scikit_learn.py\", line 151, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/engine/training.py\", line 1239, in fit\n",
      "    validation_freq=validation_freq)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/engine/training_arrays.py\", line 196, in fit_loop\n",
      "    outs = fit_function(ins_batch)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py\", line 3476, in __call__\n",
      "    run_metadata=self.run_metadata)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py\", line 1472, in __call__\n",
      "    run_metadata_ptr)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/9g/15wmnj2j4913201hs60_m1sh0000gn/T/ipykernel_74337/344838209.py\", line 5, in <module>\n",
      "    lstm_iter_model.fit(x_train,y_train,callbacks=[save_point])\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/wrappers/scikit_learn.py\", line 209, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/wrappers/scikit_learn.py\", line 151, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/engine/training.py\", line 1239, in fit\n",
      "    validation_freq=validation_freq)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/engine/training_arrays.py\", line 196, in fit_loop\n",
      "    outs = fit_function(ins_batch)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py\", line 3476, in __call__\n",
      "    run_metadata=self.run_metadata)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py\", line 1472, in __call__\n",
      "    run_metadata_ptr)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3474, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2080, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/9g/15wmnj2j4913201hs60_m1sh0000gn/T/ipykernel_74337/344838209.py\", line 5, in <module>\n",
      "    lstm_iter_model.fit(x_train,y_train,callbacks=[save_point])\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/wrappers/scikit_learn.py\", line 209, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/wrappers/scikit_learn.py\", line 151, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/engine/training.py\", line 1239, in fit\n",
      "    validation_freq=validation_freq)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/keras/engine/training_arrays.py\", line 196, in fit_loop\n",
      "    outs = fit_function(ins_batch)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py\", line 3476, in __call__\n",
      "    run_metadata=self.run_metadata)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py\", line 1472, in __call__\n",
      "    run_metadata_ptr)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3474, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2080, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3396, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2080, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2077, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/Users/virgil_lee/Downloads/anaconda/anaconda3/envs/untitled2/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "train_test_acc=[]\n",
    "lstm_iter_model=KerasClassifier(build_fn=LSTM_model, epochs=50, batch_size=10)\n",
    "save_point=LambdaCallback(on_epoch_end=lambda epochs,logs:train_test_acc.append([accuracy_score(y_train,lstm_iter_model.predict(x_train)),\n",
    "                                                                                 accuracy_score(y_test,lstm_iter_model.predict(x_test))]))\n",
    "lstm_iter_model.fit(x_train,y_train,callbacks=[save_point])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "10fb935f",
   "metadata": {
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "outputs": [],
   "source": [
    "df_lstm=pd.DataFrame(train_test_acc,columns=['train_acc','test_acc'])\n",
    "epoch=np.arange(1,len(df_lstm)+1)\n",
    "df_lstm.index=epoch\n",
    "print(df_lstm)\n",
    "plt.figure(figsize=(10,5))\n",
    "plt.plot(epoch,df_lstm['train_acc'],c='r',label='train_set_accuracy')\n",
    "plt.plot(epoch,df_lstm['test_acc'],c='b',label='test_set_accuracy')\n",
    "plt.xlabel('epoch')\n",
    "plt.ylabel('acc')\n",
    "plt.legend()\n",
    "plt.show("
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
